### ISSUE TITLE
About using SVO

### ISSUE THREAD

**Issue by MertEgeCAN** [jureviciusr/AIRDatasetPublisher#1]
Hello,

While using this dataset with SVO algorithm, I get very small x-y point values. For example when the UAV should be at 200 meters in X axis, I get 10 meters in X axis. SVO only uses "image_raw" topic and in RVIZ i can see UAV is flying at ground level. How do I configure the SVO parameters so the algorithm calculates the coordinates for flying at high altitude.

**Comment by jureviciusr** [comment]
The SVO uses default initial position (0.0, 0.0, 1.0), this position can be set using parameters in your launch file, altitude is `init_tz` as far as I remember [[svo source](https://github.com/uzh-rpg/rpg_svo/blob/d6161063b47f36ce78252ee4c4fedf3f6d8f2898/svo_ros/src/vo_node.cpp#L82)].

It was some time ago when I launched the SVO processing, but it might also require to set the `map_scale` parameter [[svo config](https://github.com/uzh-rpg/rpg_svo/blob/d6161063b47f36ce78252ee4c4fedf3f6d8f2898/svo/src/config.cpp#L31)]. Please try running with initial altitude, if the movements are not up to scale, then this parameter might also requires to be changed. I will dig up my project files to see what exact value I was using to achieve correct scaling, will get back to you later.

**Comment by MertEgeCAN** [comment]
First of all thank you for your concern and fast reply.

- As a first step, I set `init_tz` to 300 meters without touching the `map_scale` but didn't work. The x-y values were still small.
- Next I set `map_scale` to 300 straight forward (which is wrong) and I did see x-y values change drastically. This time very large values compared to ground truth.

Therefor, I think there is a formula for calculating the correct `map_scale` value for the relative altitude.

**Comment by MertEgeCAN** [comment]
I will share my parameter setup and output values. I am using the UC-300 dataset.

### First Setup

In this setup, I just converted the horizontal FOV value of gazebo camera to degrees and set it to `cam_fx` and `cam_fy`. 

**Pinhole Camera Parameters**

- `cam_width` = 640
- `cam_height` = 480
- `cam_fx` = 80
- `cam_fy` = 80
- `cam_cx` = 320
- `cam_cy` = 240
- `cam_d0`, `cam_d1`, `cam_d2`, `cam_d3` = 0

**Lauch File Parameters**

- `init_rx` = 3.14
- `init_ry` = 0
- `init_rz` = 0
- `init_tz` = 300

**Output**

Using `/svo/pose` topic:

- `x` value is between 0 and 23 meters
- `y` value is between -8 and 13 meters

### Second Setup

This time, I calculated the `cam_fx` and `cam_fy` values using the following formula.

1. a = Horizontal FOV / 2 = 57 / 2
2. A = Horizontal Resolution / 2 = 640 / 2
3. F = A / tan(a) = 320 / tan(28.5) = 589 pixels

**Pinhole Camera Parameters**

- `cam_width` = 640
- `cam_height` = 480
- `cam_fx` = 589
- `cam_fy` = 589
- `cam_cx` = 320
- `cam_cy` = 240
- `cam_d0`, `cam_d1`, `cam_d2`, `cam_d3` = 0

**Lauch File Parameters**

- `init_rx` = 3.14
- `init_ry` = 0
- `init_rz` = 0
- `init_tz` = 300

**Output**

Using `/svo/pose` topic:

- `x` value is between -2 and 103 meters
- `y` value is between -31 and 65 meters

**Comment by jureviciusr** [comment]
I have looked up my project, I have calculated the map_scale parameter using this formula:
`scale = ((double) imageWidth / 2.0) / (tan(hfov / 2.0) * altitude);`

hfov=57.3
imageWidth=640
altitude=200

So the scale I got is around ~2.93 for 200 meters altitude. Try setting that value for map_scale and see whether the trajectory is correct then. As I have looked up, I used map_scale = 1.0 and after every SVO iteration, I have recalculated the scale and applied the scale to the latest movement. (The scale is constant in the original SVO package)

**Comment by MertEgeCAN** [comment]
Hello again, I just wanted to thank you for your guidance and share my final output.

I did achieve some reliable results with the change of `map_scale` value. Only thing I did differently is, with your formula I found `map_scale` value to be ~2 (1.965 exactly). But I got good results when the value is 200 (about 100 times of formula). Maybe its because some calculations I did wrong on other steps.

With the following parameters, I did get very similar results to the ground truth.

**Pinhole Camera Parameters**

`cam_width` = 640
`cam_height` = 480
`cam_fx` = 585
`cam_fy` = 585
`cam_cx` = 320
`cam_cy` = 240
`cam_d0`, `cam_d1`, cam_d2`, `cam_d3` = 0

**Lauch File Parameters**

`init_rx` = 3.14
`init_tz` = 300
`map_scale` = 200

**Output**

_RED_ : Ground Truth
_BLUE_ : My Output
_GREEN_ : SVO Estimate

![200_fast](https://user-images.githubusercontent.com/22550479/83865361-c396de00-a72e-11ea-97f9-a2e4958402b2.png)
